### ISSUE TITLE
Multiple files

### ISSUE THREAD

**Issue by xenei** [dungwinux/pac_patcher#1]
Hello, thank you for sharing. It works like a charm, but I have noticed it can only patch 1 file at a time
Would it be possible to have support for multiple files? Since scripts files are always in masses, I have like 97 files to patch from
Doing one by one timely is a bit troublesome in the long run
Thank you.

**Comment by dungwinux** [comment]
Thanks for the report. After reviewing, this is confirmed to be a bug: the program will only patch until the first modified file.

A fix is in the work.

**Comment by dungwinux** [comment]
Fixed in d913bae...13e5c05
